export interface SubwayInfo {
    "beginRow": null | number,
    "endRow": null | number,
    "curPage": null | number,
    "pageRow": null | number,
    "totalCount": number,
    "rowNum": number,
    "selectedCount": number,
    "subwayId": string,
    "subwayNm": null,
    "updnLine": string,
    "trainLineNm": string,
    "subwayHeading": null,
    "statnFid": string,
    "statnTid": string,
    "statnId": string,
    "statnNm": string,
    "trainCo": null | string,
    "trnsitCo": string,
    "ordkey": string,
    "subwayList": string,
    "statnList": string,
    "btrainSttus": string,
    "barvlDt": string,
    "btrainNo": string,
    "bstatnId": string,
    "bstatnNm": string,
    "recptnDt": string,
    "arvlMsg2": string,
    "arvlMsg3": string,
    "arvlCd": string,
    "lstcarAt": string;
}